version: "3"

volumes:
  production_postgres_data: {}
  production_django_media: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: {{ cookiecutter.project_slug }}_production_django
    volumes:
      - production_django_media:/app/{{ cookiecutter.project_slug }}/media
    depends_on:
      - postgres
    ports:
      - 5000:5000
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: {{ cookiecutter.project_slug }}_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.production/.postgres

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: {{ cookiecutter.project_slug }}_local_nginx
    depends_on:
      - django
    ports:
      - 5050:80
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
